"""Add amount to category

Revision ID: 527b6ec6b7ed
Revises: b4dafe6e4e04
Create Date: 2023-06-27 16:45:22.066769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527b6ec6b7ed'
down_revision = 'b4dafe6e4e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
