"""Remove unique constraint from name attribute on user table

Revision ID: 984d284b988f
Revises: a175c28baa3b
Create Date: 2023-07-31 12:32:15.446763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d284b988f'
down_revision = 'a175c28baa3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_name', ['name'])

    # ### end Alembic commands ###
